[workspace]
resolver = "2"

members = [
  "clover-hub",
  "toolbox/carbon-steel",
  "toolbox/ratchet",
  "core/libs/tesseract",
  "core/libs/carbon-fiber"
, "clover-hub-macros"]

# [profile.dev]
# opt-level = 1
# 
# [profile.dev.package."*"]
# opt-level = 3
