[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
  # Make sure that tokio console works
  "--cfg",
  "tokio_unstable"
]
